### ISSUE TITLE
Feed update

### ISSUE THREAD

**Issue by vip1131** [nickersk/openpli-5#1]
Hello! Does the collected image use a feed for updates from OpenPlay or from you?

**Comment by nickersk** [comment]
hi,3rd party goes from openpli, everything else from mine own build server...

now i am working on enigma compilation errors with gcc 7.1.0  in master-next branch. i just finished build with new testing kernel in master branch. i own vusolose v2 so i build images primarilly for that machine.

**Comment by vip1131** [comment]
Do you understand Russian?

**Comment by nickersk** [comment]
with use of translator only, sorry

**Comment by vip1131** [comment]
Can you collect the image for the receiver formuler3 and give for the test?

**Comment by nickersk** [comment]
enigma2 wont compile with gcc 7.1.0 ... if you wish i can try with gcc 6.3.0

**Comment by vip1131** [comment]
Yes of course you can and so.

**Comment by nickersk** [comment]
ok, i'll try, will notice you :-)

**Comment by nickersk** [comment]
i created new repo - images, you can try image for F3 from there

**Comment by vip1131** [comment]
Thank you very much!

**Comment by nickersk** [comment]
You're welcome 👍

**Comment by vip1131** [comment]
Можете поделится инструкцией как вы собирали имидж?

**Comment by nickersk** [comment]
You can find how to build images on OpenPLi forum, or for example http://users.telenet.be/spstefansp/openpliubuntu.html Porting Openembedded layer to suite OpenPLi needs took me months of work, - what i did in sources, etc. you'll find in commits in this repo :-)

**Comment by vip1131** [comment]
Can I ask you to collect for F3 only from the original OpenPli repo?

**Comment by nickersk** [comment]
u mean feeds URIs change to openpli?

**Comment by vip1131** [comment]
Yes, collect here https://github.com/OpenPLi/openpli-oe-core

**Comment by nickersk** [comment]
whole repo is built from there,so no change is needed.

**Comment by vip1131** [comment]
Thank you for what you are doing!

**Comment by nickersk** [comment]
Thank you 👍

**Comment by vip1131** [comment]
Why did you delete the repository images?

**Comment by nickersk** [comment]
Because github lfs wants me to buy more bandwidth...

**Comment by vip1131** [comment]
Got it.

**Comment by vip1131** [comment]
Can you once again compile the image under Formuler3 and put it on some kind of exchange?

**Comment by nickersk** [comment]
no problem, just give me idea where to place it ...

**Comment by vip1131** [comment]
For example, you can here http://dropmefiles.com/

**Comment by nickersk** [comment]
http://nickersk.4shared.com

**Comment by vip1131** [comment]
Thank you.

**Comment by vip1131** [comment]
How can you be contacted, except here?

**Comment by nickersk** [comment]
nickersk@gmail.com

Dňa 5. 7. 2017 4:11 PM používateľ "vip1131" <notifications@github.com>
napísal:
